# Spring
spring:
  application:
    name: fae-team-4-service
  profiles:
    active: local
  # Hibernate ddl auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  # Spring Data Rest
  data:
    rest:
      basePath: /team-4
      return-body-on-create: true
      return-body-on-update: true
      default-media-type: application/hal+json
  # JSON Pretty Print
  jackson:
    serialization:
      indent-output: true
    deserialization:
      accept-empty-array-as-null-object: true
  kafka:
    enabled: false
    group-id: "fae-team-4-service"
    producer:
      product:
        topic: "alarmknopfhilferuf"
      alarmknopf:
        topic: "alarmknopf"
        types:
          updateType: "alarmknopf-created"
          deleteType: "alarmknopf-deleted"
    consumer:
      tracker:
        topic: "demenziellErkrankte"
      position:
        topic: "tracker"

# Server
server:
  port: 8080
  compression.enabled: true
  compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain

# Messaging system
messagingSystem.url: "lb://fae-team-3-service/ausnahmesituation/"

# Logging Level
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
