server:
  port: 8081
spring:
  # Kafka
  kafka:
    enabled: true
    bootstrap-servers: localhost:9092
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
