# Database
spring:
  datasource:
    url: jdbc:postgresql://${TEAM4_DB}:5432/${TEAM4_DB_NAME}
    password: ${TEAM4_DB_PW}
    username: ${TEAM4_DB_USER}
  # kafka servers
  kafka:
    enabled: false
    bootstrap-servers: kafka:9092

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/
    enabled: false
server:
  servlet:
    session:
      cookie:
        domain: localhost
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
