version: "3.7"

services:
  postgres:
    image: postgres:10.1
    volumes:
      - fae-team-4-service_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=zuckerschnecken
      - POSTGRES_USER=team4
      - POSTGRES_DB=team4
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - service_internal
  springboot-service:
    image: docker.nexus.archi-lab.io/archilab/fae-team-4-service
    environment:
      - TZ=Europe/Berlin
      - TEAM4_DB=postgres
      - TEAM4_DB_NAME=team4
      - TEAM4_DB_USER=team4
      - TEAM4_DB_PW=zuckerschnecken
    depends_on:
      - postgres
    networks:
      - service_internal
      - fae_backend

volumes:
  fae-team-4-service_db: {}

networks:
  service_internal:
  fae_backend:
    external: true
